In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/survey_results_public.csv', low_memory=False, index_col='ResponseId')
schema_df = pd.read_csv('data/survey_results_schema.csv', index_col='qname')

In [3]:
pd.set_option('display.max_columns', 172)
pd.set_option('display.max_rows', 139)

In [4]:
df.head()

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [13]:
df.sort_values(by=['Country', 'CompTotal'],ascending=[True, False], inplace=True)

In [14]:
df[['Country', 'CompTotal']].head(50)

                Country   CompTotal
ResponseId
40307       Afghanistan    700000.0
7077        Afghanistan    600000.0
45925       Afghanistan    500000.0
6010        Afghanistan     70000.0
40967       Afghanistan     65000.0
7925        Afghanistan     20000.0
7167        Afghanistan      5200.0
38609       Afghanistan      1000.0
6836        Afghanistan         NaN
15708       Afghanistan         NaN
19816       Afghanistan         NaN
44797       Afghanistan         NaN
27099       Afghanistan         NaN
28588           Albania  10004806.0
37731           Albania   5732910.0
33940           Albania   1500000.0
3888            Albania   1200000.0
2023            Albania    120000.0
3185            Albania     99999.0
35934           Albania     50000.0
14758           Albania     30000.0
16850           Albania     20000.0
48950           Albania     15000.0
22400           Albania        56.0
27802           Albania         7.0
36997           Albania         NaN
35184           Albania         NaN
16239           Albania         NaN
45421           Albania         NaN
44879           Albania         NaN
44946           Albania         NaN
8776            Albania         NaN
11874           Albania         NaN
41907           Albania         NaN
25304           Albania         NaN
26446           Algeria   3000000.0
29465           Algeria   1000000.0
16686           Algeria    920000.0
30107           Algeria    840000.0
1841            Algeria    576000.0
31352           Algeria    500000.0
14548           Algeria    150000.0
34029           Algeria    144000.0
41296           Algeria     85000.0
37619           Algeria     50000.0
25845           Algeria     24000.0
1541            Algeria     18000.0
23091           Algeria     12000.0
46636           Algeria      2400.0
11322           Algeria        15.0

In [18]:
schema_df.loc['CompTotal']['question']

'What is your current total <b>annual</b> compensation (salary, bonuses, and perks, before taxes and deductions) in terms of your day-to-day currency?  Please enter a whole number in the box below, without any punctuation.  If you are paid hourly, please estimate an equivalent yearly salary. If you prefer not to answer, please leave the box empty. '

In [19]:
df['CompTotal'].nlargest(10)

ResponseId
4934     5.555556e+74
44527    8.000000e+23
35765    1.000000e+23
28546    9.223372e+18
22733    1.000000e+17
484      1.000000e+16
18755    1.000000e+15
39338    9.596957e+11
35354    6.500000e+11
39350    1.000000e+11
Name: CompTotal, dtype: float64

In [22]:
df.nlargest(5, 'CompTotal')

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
4934,I am a developer by profession,45-54 years old,Other (please specify):,I prefer not to say,NaN,100.0,"Yes, I am new to coding or currently a student",Other (please specify):,"No, I didn't spend time learning in the past year",NaN,100.0,Other (please specify):,NaN,NaN,NaN,NaN,Personal Project,8.0,7.0,6.0,3.0,10.0,5.0,2.0,9.0,4.0,1.0,FUCK SUPPORT FROM SO!,8.0,5.0,4.0,9.0,6.0,7.0,10.0,3.0,2.0,1.0,FUCK SUPPORT FROM SO!,NaN,12.0,10.0,14.0,9.0,4.0,13.0,11.0,3.0,8.0,6.0,2.0,7.0,5.0,1.0,15.0,FUCK SUPPORT FROM SO!,Yes,NaN,100.0,100.0,United States of America,USD United States dollar,5.555556e+74,NaN,NaN,NaN,NaN,FUCK SUPPORT FROM SO!,FUCK SUPPORT FROM SO!,NaN,NaN,NaN,NaN,FUCK SUPPORT FROM SO!,FUCK SUPPORT FROM SO!,NaN,NaN,NaN,NaN,FUCK SUPPORT FROM SO!,FUCK SUPPORT FROM SO!,NaN,NaN,NaN,NaN,FUCK SUPPORT FROM SO!,FUCK SUPPORT FROM SO!,NaN,NaN,NaN,NaN,FUCK SUPPORT FROM SO!,FUCK SUPPORT FROM SO!,NaN,NaN,NaN,FUCK SUPPORT FROM SO!,FUCK SUPPORT FROM SO!,NaN,NaN,NaN,NaN,NaN,FUCK SUPPORT FROM SO!,FUCK SUPPORT FROM SO!,NaN,NaN,NaN,FUCK SUPPORT FROM SO!,FUCK SUPPORT FROM SO!,NaN,NaN,NaN,NaN,FUCK SUPPORT FROM SO!,FUCK SUPPORT FROM SO!,Not sure/can't remember,"Infrequently, less than once per year","More than 15 years, or since Stack Overflow st...",NaN,Other (write in):,8.0,6.0,1.0,5.0,2.0,7.0,3.0,9.0,4.0,10.0,FUCK SUPPORT FROM SO!,Not sure,"Rarely, almost never","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other (write in):,Other (write in):,FUCK SUPPORT FROM SO!,"No, and I don't plan to","No, but my development work has significantly ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Write in the most significant challenge if not...,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other (please specify):,FUCK SUPPORT FROM SO!,NaN,0.0
44527,I am a developer by profession,18-24 years old,Other (please specify):,I prefer not to say,NaN,100.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",NaN,1.0,Other (please specify):,NaN,NaN,NaN,NaN,Personal Project,2.0,6.0,8.0,9.0,1.0,7.0,5.0,3.0,4.0,10.0,My new company in Nepal Ramjuce,1.0,2.0,4.0,3.0,8.0,6.0,5.0,7.0,9.0,10.0,How to create a money the I hard work,NaN,2.0,10.0,9.0,6.0,12.0,1.0,13.0,8.0,5.0,11.0,14.0,4.0,7.0,15.0,3.0,This my money depression,Yes,I have neither consider or transitioned into a...,1000.0,1000.0,Nepal,USD United States dollar,8.000000e+23,NaN,Ada;Assembly;Bash/Shell (all shells);C;C#;C++;...,NaN,NaN,I am no using a coading,Fake,Yes,BigQuery;Cassandra;Cloud Firestore;Cosmos DB;D...,NaN,NaN,I am using only PC and cpu,Duckduckgo,Yes,Amazon Web Services (AWS);Ansible;APT;Bun;Carg...,Amazon Web Services (AWS);Ansible;APT;Bun;Carg...,Amazon Web Services (AWS);Ansible;APT;Bun;Carg...,I am a new man in the world,I am new man in the world,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"No, and I don't plan to",Indifferent,Neither trust nor distrust,I don't use AI tools for complex tasks / I don...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,Other (write in):;I haven’t encountered any pr...,I am note using Wikipedia,"Yes, I use AI agents at work weekly","No, but my development work has significantly ...",Business process automation;Other Industry pur...,MCP servers;Other specific task (write in):,NaN,NaN,NaN,AI agents have increased my productivity.;AI a...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,GitHub MCP Server,"Binance,Exness,b2p,p2psystem,Reedit",Vertex AI;Agno;AutoGen (Microsoft);CrewAI;IBM ...,1,Sentry;Galileo;Honeycomb;Metero;New Relic;opik...,1,ChatGPT;Claude Code;GitHub Copilot;Google Gemi...,1,When I don’t trust AI’s answers;When I want to...,My vailu is 0,NaN,NaN
35765,I am a developer by profession,55-64 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",Engaged in paid work (20-29 hours per week),27.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",NaN,31.0,Retired,"Just me - I am a freelancer, sole proprietor, ...",NaN,NaN,"Yes, I endorsed a tool that was ultimately not...",Work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Manufacturing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,I have neither consider or transitioned into a...,6.0,NaN,India,INR Indian rupee,1.000000e+23,Yes,NaN,NaN,NaN,R html,C Assembly R Latex Html,Yes,NaN,NaN,NaN,NaN,Linux,Yes,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ubuntu,GitHub;Monday.com,NaN,NaN,NaN,NaN,Stack Overflow,"Stack Overflow;GitHub (public projects, not pr...",Stack Overflow,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,A few times per month or weekly,Chat (people);Videos;Coding challenges,6.0,9.0,4.0,1.0,7.0,8.0,2.0,3.0,5.0,10.0,ThankYoi,"Yes, somewhat",I don't use AI or AI-enabled tools,NaN,Unfavorable,Highly distrust,I don't use AI tools for complex tasks / I don...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,It’s hard to understand how or why the code works,No more wikipedia,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,NaN,NaN,NaN
28546,I am learning to code,Prefer not to say,"Secondary school (e.g. American high school, G...",I prefer not to say,NaN,NaN,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I didn't spend time learning in the past year",NaN,4.0,Student,NaN,NaN,NaN,NaN,Personal Project,9.0,7.0,8.0,4.0,3.0,6.0,5.0,1.0,2.0,10.0,NaN,9.0,5.0,6.0,4.0,3.0,2.0,1.0,7.0,8.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,I have neither consider or transitioned into a...,10000.0,3.0,"Micronesia, Federated States of...",USD United States dollar,9.223372e+18,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Nano;Neovim;Notepad++;Vim;Visual Studio Code,NaN,NaN,NaN,Bussin GriddyCode,NaN,NaN,NaN,NaN,NaN,Windows;Android;Linux (non-WSL),Windows,GitHub,GitHub,GitHub,NaN,NaN,Stack Overflow;Stack Exchange;Reddit;GitHub (p...,NaN,NaN,NaN,NaN,Yes,DeepSeek (V- General purpose models);openAI GP...,openAI GPT (chatbot models);openAI Reasoning m...,openAI GPT (chatbot models);openAI Reasoning m...,NaN,NaN,No,Less than once per month or monthly,Between 1 and 3 years,I have never participated in Q&A on Stack Over...,NaN,9.0,4.0,5.0,1.0,8.0,7.0,6.0,3.0,2.0,10.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Learning about a codebase;Project planning;Deb...,Documenting code;Testing code;Deployment and m...,Writing code,NaN,Search for answers;Generating content or synth...,Other (write in):,idk,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,using the computer,NaN,NaN
22733,I work with developers or my work supports dev...,65 years or older,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",Engaged in paid work (20-29 hours per week),5.0,"Yes, I am not new to coding but am learning ne...",Stack Overflow or Stack Exchange;AI CodeGen to...,"No, I learned something that was not related t...",NaN,100.0,"Founder, technology or otherwise","Just me - I am a freelancer, sole proprietor, ...",People manager,"Hybrid (some remote, leans heavy to in-person)","Yes, I endorsed a tool that was ultimately not...",Personal Project,5.0,10.0,4.0,3.0,8.0,1.0,2.0,7.0,6.0,9.0,Ralf P Carreon,6.0,7.0,5.0,3.0,8.0,2.0,9.0,1.0,4.0,10.0,NaN,Manufacturing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,I have neither consider or transitioned into a...,NaN,NaN,Philippines,USD United States dollar,1.000000e+17,No,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,Ralf P Carreon,Gcash.com,No,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,office,Ralf P Carreon,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IO,IO,Android,NaN,NaN,NaN,NaN,IO,ralfpcarreon29@gmail.com,NaN,NaN,NaN,Ralf P Carreon,Elon musk,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 10 and 15 years,Daily or almost daily,Long-form articles;Other (write in):,9.0,8.0,1.0,3.0,4.0,6.0,2.0,5.0,7.0,10.0,Ralf P Carreon,Neutral,Less than half of the time,"Yes, I use AI tools monthly or infrequently",Very unfavorable,Highly trust,Very well at handling complex tasks,NaN,Learning about a codebase;Writing code;Debuggi...,Documenting code;Deployment and monitoring;Pre...,Project planning;Testing code,NaN,I’ve become less confident in my own problem-s...,ralfpcarreon29@gmail.com,"No, but I plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I’m stuck and can’t explain the problem;O...,35,NaN,NaN

In [23]:
df.nsmallest(5, 'CompTotal')

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
7106,"I am not primarily a developer, but I write co...",18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Attending school (full-time),4.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...","School (i.e., University, College, etc)",4.0,Student,NaN,NaN,NaN,NaN,School,5.0,3.0,8.0,2.0,4.0,6.0,9.0,7.0,1.0,10.0,NaN,5.0,7.0,1.0,3.0,9.0,6.0,4.0,2.0,8.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I'm not sure,I have transitioned into a new career and/or i...,2.0,2.0,Algeria,DZD\tAlgerian dinar,0.0,No,NaN,NaN,NaN,NaN,NaN,Yes,Firebase Realtime Database;MySQL;PostgreSQL;SQ...,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,Django;Spring Boot,Angular;Spring Boot,Spring Boot,NaN,NaN,Yes,Android Studio;Eclipse;IntelliJ IDEA,Android Studio;IntelliJ IDEA;Visual Studio Code,Android Studio;IntelliJ IDEA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;Debian,Windows;Debian,GitHub,GitHub;GitLab;Jira,GitHub,NaN,NaN,LinkedIn,Stack Overflow;LinkedIn,LinkedIn,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Not sure/can't remember,NaN,Between 1 and 3 years,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools daily",Favorable,Somewhat trust,"Good, but not great at handling complex tasks",Predictive analytics,Project planning;Documenting code,Testing code;Creating or maintaining documenta...,NaN,Learning about a codebase;Writing code;Debuggi...,I don’t use AI tools regularly,no,"Yes, I use AI agents at work daily","Yes, to a great extent",Software engineering,Integration with external agents and APIs,NaN,NaN,NaN,AI agents have increased my productivity.;AI a...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Google Gemini,NaN,When I’m stuck and can’t explain the problem,NaN,NaN,NaN
28573,I code primarily as a hobby,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Student,NaN,3.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",NaN,10.0,Student,NaN,NaN,NaN,NaN,Personal Project,10.0,3.0,4.0,8.0,6.0,5.0,2.0,7.0,1.0,9.0,Actively maintained,10.0,4.0,8.0,5.0,2.0,7.0,3.0,6.0,1.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,I have neither consider or transitioned into a...,NaN,4.0,Algeria,DZD\tAlgerian dinar,0.0,Yes,C#;Python,C#;HTML/CSS;JavaScript;Python;R;SQL,C#;Python,NaN,NaN,Yes,PostgreSQL;SQLite,MySQL;PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,Yes,Microsoft Azure;MSBuild;NuGet;Pip,Amazon Web Services (AWS);Cloudflare;Docker;Mi...,Microsoft Azure;MSBuild;NuGet;Pip,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Yes,Visual Studio;Visual Studio Code,Visual Studio;Visual Studio Code,Visual Studio;Visual Studio Code,NaN,NaN,.NET 8 or higher;Odoo,.NET 8 or higher;Large Language Model;Google G...,.NET 8 or higher,NaN,NaN,Windows;Android,Windows,GitHub;Markdown File,GitHub;Markdown File,GitHub;Markdown File,NaN,NaN,Stack Overflow;Stack Exchange;Discord;GitHub (...,Stack Overflow;Stack Exchange;Discord;GitHub (...,Stack Overflow;Stack Exchange;Discord;GitHub (...,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Daily or almost daily,Between 5 and 10 years,Less than once every 2 - 3 months,Coding challenges;Logic games/puzzles,7.0,1.0,8.0,6.0,4.0,5.0,3.0,2.0,9.0,10.0,NaN,"No, not really",I don't use AI or AI-enabled tools,"No, and I don't plan to",Very unfavorable,Neither trust nor distrust,I don't use AI tools for complex tasks / I don...,NaN,NaN,NaN,NaN,NaN,I don’t use AI tools regularly,"NO, NO, NOOO! How many times should I keep say...","No, and I don't plan to","No, but my development work has changed somewh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,The cost of using certain AI agent platforms i...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,I don't think AI tools will become more capable,NaN,NaN
27412,I am a developer by profession,18-24 years old,"Secondary school (e.g. American high school, G...",Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps,3.0,Student,NaN,NaN,NaN,NaN,Work,8.0,1.0,3.0,4.0,2.0,5.0,6.0,7.0,9.0,10.0,NaN,9.0,1.0,2.0,4.0,5.0,3.0,7.0,6.0,8.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I'm not sure,I have neither consider or transitioned into a...,3.0,3.0,Algeria,DZD\tAlgerian dinar,0.0,Yes,C;HTML/CSS;JavaScript;Python;Rust;SQL;TypeScript,HTML/CSS;JavaScript;PHP;SQL;TypeScript,HTML/CSS;JavaScript;SQL;TypeScript,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Astro;Next.js;Node.js;React;Svelte,Laravel;Next.js;Node.js;React,Next.js;Node.js;React,NaN,NaN,Yes,IntelliJ IDEA;Visual Studio Code,Visual Studio Code,Visual Studio Code,NaN,NaN,Tailwind CSS 4;Large Language Model;Shadcn/ui,Tailwind CSS 4;Large Language Model;Shadcn/ui,Tailwind CSS 4;Large Language Model;Shadcn/ui,NaN,NaN,Linux (non-WSL);Arch,Linux (non-WSL);Arch,GitHub;Lucid (includes Lucidchart),GitHub;Lucid (includes Lucidchart),GitHub;Lucid (includes Lucidchart),NaN,NaN,Stack Overflow;Stack Exchange;Reddit;YouTube,Stack Overflow;Stack Exchange;Reddit;YouTube;L...,Stack Overflow;Stack Exchange;Reddit;YouTube,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Reasoning m...,DeepSeek (R- Reasoning models),NaN,NaN,NaN,Yes,Daily or almost daily,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Chat (people);Coding challenges;Logic games/pu...,3.0,2.0,4.0,1.0,9.0,8.0,7.0,5.0,6.0,10.0,NaN,"No, not really",Less than half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,I don't use AI tools for complex tasks / I don...,Writing code;Committing and reviewing code;Sea...,NaN,Project planning;Testing code;Deployment and m...,Learning about a codebase;Documenting code;Cre...,Debugging or fixing code;Generating content or...,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Theoretical knowledge.,NaN,NaN
49028,I am learning to code,25-34 years old,Some college/university study without earning ...,Not employed,None of the above,5.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"No, I didn't spend time learning in the past year",NaN,8.0,"Developer, full-stack",NaN,NaN,NaN,NaN,Work,8.0,9.0,1.0,4.0,6.0,2.0,3.0,5.0,7.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,I have neither consider or transitioned into a...,0.0,5.0,Algeria,DZD\tAlgerian dinar,0.0,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Discord;Reddit;H...,Company-sponsored forums,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,"Infrequently, less than once per year",Less than one year,I have never participated in Q&A on Stack Over...,Chat (bot/AI),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Neutral,I don't use AI or AI-enabled tools,"No, but I plan to soon",Unfavorable,NaN,Bad at handling complex tasks,Project planning;Debugging or fixing code;Test...,Writing code;Creating or maintaining documenta...,NaN,Learning about a codebase;Documenting code;Pre...,Deployment and monitoring;Generating content o...,I haven’t encountered any problems,NaN,"Yes, I use AI agents at work weekly","No, but my development work has changed somewh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35174,I am learning to code,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",Engaged in paid work (20-29 hours per week),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Technical ...,5.0,Student,"Just me - I am a freelancer, sole proprietor, ...",Individual contributor,In-person,"Yes, I endorsed a tool that was ultimately not...",Work,4.0,6.0,5.0,8.0,2.0,1.0,7.0,9.0,3.0,10.0,NaN,5.0,6.0,9.0,7.0,2.0,1.0,4.0,3.0,8.0,10.0,NaN,Software Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,I have neither consider or transitioned into a...,4.0,4.0,Algeria,DZD\tAlgerian dinar,0.0,Yes,Bash/Shell (all shells);Dart;Go;HTML/CSS;Java;...,Bash/Shell (all shells);Dart,Bash/Shell (all shells);Dart,NaN,NaN,Yes,MariaDB;MongoDB;MySQL;Oracle;PostgreSQL;SQLite...,PostgreSQL;Redis,PostgreSQL,NaN,NaN,Yes,Docker;Gradle;Netlify;npm;Pacman;Pip,Cloudflare;Docker;Netlify,Docker;Netlify,NaN,NaN,Yes,NaN,NaN,NaN,"Flutter web, jaspr","Flutter web, jaspr",Yes,Android Studio;IntelliJ IDEA;Nano;Neovim;Visua...,Visual Studio Code;VSCodium,Visual Studio Code;VSCodium,NaN,NaN,Tailwind CSS 4;Large Language Model;Google Gemini,Tailwind CSS 4;Large Language Model;Google Gemini,Tailwind CSS 4;Large Language Model;Google Gemini,NaN,NaN,Windows;Ubuntu;Android;Windows Subsystem for L...,Windows;Ubuntu;Android;Windows Subsystem for L...,GitHub;GitLab;Google Workspace,GitLab;Google Workspace,GitLab;Google Workspace,NaN,NaN,Reddit;Dev.to;Hacker News;GitHub (public proje...,"Dev.to;GitHub (public projects, not private re...","Dev.to;GitHub (public projects, not private re...",NaN,NaN,Yes,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,NaN,NaN,Yes,Less than once every 2 - 3 months,Less than one year,I have never participated in Q&A on Stack Over...,NaN,2.0,1.0,8.0,7.0,3.0,4.0,5.0,9.0,6.0,10.0,NaN,"Yes, somewhat","Rarely, almost never","Yes, I use AI tools daily",Very favorable,Somewhat trust,"Good, but not great at handling complex tasks",NaN,NaN,Deployment and monitoring,Learning about a codebase;Testing code;Committ...,Project planning;Writing code;Documenting code...,Debugging AI-generated code is more time-consu...,Yes,"Yes, I use AI agents at work daily","Yes, to a great extent",Software engineering;Decision intelligence;IT ...,NaN,NaN,AI agents have improved collaboration within m...,NaN,AI agents have increased my productivity.;AI a...,NaN,The cost of using certain AI agent platforms i...,NaN,I have concerns about the security and privacy...,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,Ollama,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemi...,NaN,When I don’t trust AI’s answers;I don’t think ...,NaN,NaN,NaN