In [1]:
people = {
    "first": ["Mansi", "Manan", "Komal", "Sujal"],
    "last": ["Kothari", "Jain", "Kothari", "Jain"],
    "email": ["mansikothari46@gmail.com", "kotharimanan46@gmail.com", "komalexample@gmail.com", "sujalexample@gmail.com"]
}

In [2]:
people['email']

['mansikothari46@gmail.com',
 'kotharimanan46@gmail.com',
 'komalexample@gmail.com',
 'sujalexample@gmail.com']

In [3]:
import pandas as pd

In [4]:
df = pd.DataFrame(people)

In [5]:
df

   first     last                     email
0  Mansi  Kothari  mansikothari46@gmail.com
1  Manan     Jain  kotharimanan46@gmail.com
2  Komal  Kothari    komalexample@gmail.com
3  Sujal     Jain    sujalexample@gmail.com

In [8]:
df.sort_values(by='first', ascending=False)

   first     last                     email
3  Sujal     Jain    sujalexample@gmail.com
0  Mansi  Kothari  mansikothari46@gmail.com
1  Manan     Jain  kotharimanan46@gmail.com
2  Komal  Kothari    komalexample@gmail.com

In [13]:
df.loc[4] = ['Sujal', 'Malhotra', 'suajlmalhotra@gmail.com']

In [14]:
df

   first      last                     email
0  Mansi   Kothari  mansikothari46@gmail.com
1  Manan      Jain  kotharimanan46@gmail.com
2  Komal   Kothari    komalexample@gmail.com
3  Sujal      Jain    sujalexample@gmail.com
4  Sujal  Malhotra   suajlmalhotra@gmail.com

In [15]:
df.sort_values(by=['first', 'last'], ascending=False)

   first      last                     email
4  Sujal  Malhotra   suajlmalhotra@gmail.com
3  Sujal      Jain    sujalexample@gmail.com
0  Mansi   Kothari  mansikothari46@gmail.com
1  Manan      Jain  kotharimanan46@gmail.com
2  Komal   Kothari    komalexample@gmail.com

In [16]:
df.loc[5] = ['Sujal', 'Kothari', 'suajlkothari@gmail.com']

In [18]:
df.sort_values(by=['first', 'last'], ascending=[False, True], inplace = True)

In [19]:
df

   first      last                     email
3  Sujal      Jain    sujalexample@gmail.com
5  Sujal   Kothari    suajlkothari@gmail.com
4  Sujal  Malhotra   suajlmalhotra@gmail.com
0  Mansi   Kothari  mansikothari46@gmail.com
1  Manan      Jain  kotharimanan46@gmail.com
2  Komal   Kothari    komalexample@gmail.com

In [20]:
df.sort_index()

   first      last                     email
0  Mansi   Kothari  mansikothari46@gmail.com
1  Manan      Jain  kotharimanan46@gmail.com
2  Komal   Kothari    komalexample@gmail.com
3  Sujal      Jain    sujalexample@gmail.com
4  Sujal  Malhotra   suajlmalhotra@gmail.com
5  Sujal   Kothari    suajlkothari@gmail.com

In [21]:
df['last'].sort_values()

3        Jain
1        Jain
5     Kothari
0     Kothari
2     Kothari
4    Malhotra
Name: last, dtype: str